########## CLOCK  100M ##########
#set_property PACKAGE_PIN U24 [get_ports clk]
#set_property IOSTANDARD LVCMOS25 [get_ports clk]

########## CLOCK  133M ##########
#set_property PACKAGE_PIN T25 [get_ports clk]
#set_property IOSTANDARD LVCMOS25 [get_ports clk]

########## BUTTONS ##########
#set_property PACKAGE_PIN A16  IOSTANDARD LVCMOS25 [get_ports {btn[0]}]
#set_property PACKAGE_PIN B16  IOSTANDARD LVCMOS25 [get_ports {btn[1]}]
set_property -dict { PACKAGE_PIN J24  IOSTANDARD LVCMOS25 } [get_ports {reset}]
set_false_path -from [get_ports {reset}]

########## SWITCHES ##########
#set_property PACKAGE_PIN Y24  IOSTANDARD LVCMOS25 [get_ports {sw[0]}]
#set_property PACKAGE_PIN Y23  IOSTANDARD LVCMOS25 [get_ports {sw[1]}]
#set_property PACKAGE_PIN W24  IOSTANDARD LVCMOS25 [get_ports {sw[2]}]
#set_property PACKAGE_PIN L17  IOSTANDARD LVCMOS25 [get_ports {sw[3]}]
#set_false_path -from [get_ports {sw[*]}]

########## LEDS ##########
#set_property PACKAGE_PIN A27  IOSTANDARD LVCMOS25 [get_ports {led[0]}]
#set_property PACKAGE_PIN E24  IOSTANDARD LVCMOS25 [get_ports {led[1]}]
#set_property PACKAGE_PIN G24  IOSTANDARD LVCMOS25 [get_ports {led[2]}]
#set_property PACKAGE_PIN H21  IOSTANDARD LVCMOS25 [get_ports {led[3]}]
#set_property PACKAGE_PIN G27  IOSTANDARD LVCMOS25 [get_ports {led[4]}]
#set_property PACKAGE_PIN H26  IOSTANDARD LVCMOS25 [get_ports {led[5]}]
#set_property PACKAGE_PIN H25  IOSTANDARD LVCMOS25 [get_ports {led[6]}]
#set_property PACKAGE_PIN H24  IOSTANDARD LVCMOS25 [get_ports {led[7]}]
set_property -dict { PACKAGE_PIN AE20 IOSTANDARD LVCMOS25 } [get_ports {locked[0]}]
set_property -dict { PACKAGE_PIN AC20 IOSTANDARD LVCMOS25 } [get_ports {led[0]}]
set_property -dict { PACKAGE_PIN AC19 IOSTANDARD LVCMOS25 } [get_ports {led[1]}]
set_property -dict { PACKAGE_PIN AB19 IOSTANDARD LVCMOS25 } [get_ports {led[2]}]
set_property -dict { PACKAGE_PIN AB20 IOSTANDARD LVCMOS25 } [get_ports {led[3]}]
set_property -dict { PACKAGE_PIN AA20 IOSTANDARD LVCMOS25 } [get_ports {led[4]}]
set_property -dict { PACKAGE_PIN Y20  IOSTANDARD LVCMOS25 } [get_ports {led[5]}]
set_property -dict { PACKAGE_PIN AA21 IOSTANDARD LVCMOS25 } [get_ports {led[6]}]

########### GTX CONSTRAINTS    156.25M  GTX 117 ##########
#set_property PACKAGE_PIN G8   [get_ports gtrefclk0_p]
#set_property PACKAGE_PIN G7   [get_ports gtrefclk0_n]
########### GTX CONSTRAINTS    156.25M  GTX 114 ##########
#set_property PACKAGE_PIN T6   [get_ports gtrefclk1_p]
#set_property PACKAGE_PIN T5   [get_ports gtrefclk1_n]
########### GTX CONSTRAINTS    125M  GTX 116 ##########
#set_property PACKAGE_PIN H6   [get_ports gtrefclk2_p]
#set_property PACKAGE_PIN H5   [get_ports gtrefclk2_n]
########### GTX CONSTRAINTS    125M  GTX 114 ##########
#set_property PACKAGE_PIN R8   [get_ports gtrefclk3_p]
#set_property PACKAGE_PIN R7   [get_ports gtrefclk3_n]

########### --------- SFPA --------- GTX 117 ##########
#set_property PACKAGE_PIN A17  IOSTANDARD LVCMOS25 [get_ports sfp_a_tx_disable]
#set_property PACKAGE_PIN B15  IOSTANDARD LVCMOS25 [get_ports sfp_a_rate]
#set_property PACKAGE_PIN A15  IOSTANDARD LVCMOS25 [get_ports sfp_a_scl]
#set_property PACKAGE_PIN C15  IOSTANDARD LVCMOS25 [get_ports sfp_a_sda]
#set_property PACKAGE_PIN D10  [get_ports sfp_a_rx_p]
#set_property PACKAGE_PIN D9   [get_ports sfp_a_rx_n]
#set_property PACKAGE_PIN A8   [get_ports sfp_a_tx_p]
#set_property PACKAGE_PIN A7   [get_ports sfp_a_tx_n]

########### --------- SFPB --------- GTX 117 ##########
#set_property PACKAGE_PIN D14  IOSTANDARD LVCMOS25 [get_ports sfp_b_tx_disable]
#set_property PACKAGE_PIN A14  IOSTANDARD LVCMOS25 [get_ports sfp_b_rate]
#set_property PACKAGE_PIN B14  IOSTANDARD LVCMOS25 [get_ports sfp_b_scl]
#set_property PACKAGE_PIN C14  IOSTANDARD LVCMOS25 [get_ports sfp_b_sda]
#set_property PACKAGE_PIN F10  [get_ports sfp_b_rx_p]
#set_property PACKAGE_PIN F9   [get_ports sfp_b_rx_n]
#set_property PACKAGE_PIN C8   [get_ports sfp_b_tx_p]
#set_property PACKAGE_PIN C7   [get_ports sfp_b_tx_n]

########### --------- QSFPA ------------##########
#set_property PACKAGE_PIN A17  IOSTANDARD LVCMOS25 [get_ports qsfp_a_lpmode]
#set_property PACKAGE_PIN B15  IOSTANDARD LVCMOS25 [get_ports qsfp_a_modsel]
#set_property PACKAGE_PIN A15  IOSTANDARD LVCMOS25 [get_ports qsfp_a_modprsl]
#set_property PACKAGE_PIN C15  IOSTANDARD LVCMOS25 [get_ports qsfp_a_reset]
#set_property PACKAGE_PIN A14  IOSTANDARD LVCMOS25 [get_ports qsfp_a_intl]
#set_property PACKAGE_PIN B14  IOSTANDARD LVCMOS25 [get_ports qsfp_a_scl]
#set_property PACKAGE_PIN C14  IOSTANDARD LVCMOS25 [get_ports qsfp_a_sda]
#set_property PACKAGE_PIN G3   [get_ports {qsfp_a_rx_p[0]}]
#set_property PACKAGE_PIN G4   [get_ports {qsfp_a_rx_n[0]}]
#set_property PACKAGE_PIN E3   [get_ports {qsfp_a_rx_p[1]}]
#set_property PACKAGE_PIN E4   [get_ports {qsfp_a_rx_n[1]}]
#set_property PACKAGE_PIN D5   [get_ports {qsfp_a_rx_p[2]}]
#set_property PACKAGE_PIN D6   [get_ports {qsfp_a_rx_n[2]}]
#set_property PACKAGE_PIN C3   [get_ports {qsfp_a_rx_p[3]}]
#set_property PACKAGE_PIN C4   [get_ports {qsfp_a_rx_n[3]}]
#set_property PACKAGE_PIN D1   [get_ports {qsfp_a_tx_p[0]}]
#set_property PACKAGE_PIN D2   [get_ports {qsfp_a_tx_n[0]}]
#set_property PACKAGE_PIN B1   [get_ports {qsfp_a_tx_p[1]}]
#set_property PACKAGE_PIN B2   [get_ports {qsfp_a_tx_n[1]}]
#set_property PACKAGE_PIN A3   [get_ports {qsfp_a_tx_p[2]}]
#set_property PACKAGE_PIN A4   [get_ports {qsfp_a_tx_n[2]}]
#set_property PACKAGE_PIN B5   [get_ports {qsfp_a_tx_p[3]}]
#set_property PACKAGE_PIN B6   [get_ports {qsfp_a_tx_n[3]}]

########### --------- QSFPB ------------##########
#set_property PACKAGE_PIN H15  IOSTANDARD LVCMOS25 [get_ports qsfp_b_lpmode]
#set_property PACKAGE_PIN J17  IOSTANDARD LVCMOS25 [get_ports qsfp_b_modsel]
#set_property PACKAGE_PIN G17  IOSTANDARD LVCMOS25 [get_ports qsfp_b_modprsl]
#set_property PACKAGE_PIN H17  IOSTANDARD LVCMOS25 [get_ports qsfp_b_reset]
#set_property PACKAGE_PIN F17  IOSTANDARD LVCMOS25 [get_ports qsfp_b_intl]
#set_property PACKAGE_PIN J16  IOSTANDARD LVCMOS25 [get_ports qsfp_b_scl]
#set_property PACKAGE_PIN H16  IOSTANDARD LVCMOS25 [get_ports qsfp_b_sda]
#set_property PACKAGE_PIN M5   [get_ports {qsfp_b_rx_p[0]}]
#set_property PACKAGE_PIN M6   [get_ports {qsfp_b_rx_n[0]}]
#set_property PACKAGE_PIN L3   [get_ports {qsfp_b_rx_p[1]}]
#set_property PACKAGE_PIN L4   [get_ports {qsfp_b_rx_n[1]}]
#set_property PACKAGE_PIN K5   [get_ports {qsfp_b_rx_p[2]}]
#set_property PACKAGE_PIN K6   [get_ports {qsfp_b_rx_n[2]}]
#set_property PACKAGE_PIN J3   [get_ports {qsfp_b_rx_p[3]}]
#set_property PACKAGE_PIN J4   [get_ports {qsfp_b_rx_n[3]}]
#set_property PACKAGE_PIN M1   [get_ports {qsfp_b_tx_p[0]}]
#set_property PACKAGE_PIN M2   [get_ports {qsfp_b_tx_n[0]}]
#set_property PACKAGE_PIN K1   [get_ports {qsfp_b_tx_p[1]}]
#set_property PACKAGE_PIN K2   [get_ports {qsfp_b_tx_n[1]}]
#set_property PACKAGE_PIN H1   [get_ports {qsfp_b_tx_p[2]}]
#set_property PACKAGE_PIN H2   [get_ports {qsfp_b_tx_n[2]}]
#set_property PACKAGE_PIN F1   [get_ports {qsfp_b_tx_p[3]}]
#set_property PACKAGE_PIN F2   [get_ports {qsfp_b_tx_n[3]}]

########### --------- PCIE ------------##########
#set_property PACKAGE_PIN AD5  [get_ports pcie_refclk_n]
#set_property PACKAGE_PIN AD6  [get_ports pcie_refclk_[]

#set_property PACKAGE_PIN W21  IOSTANDARD LVCMOS33 [get_ports pcie_reset_n]

#set_property PACKAGE_PIN AH9  [get_ports {pcie_rxn[7]}]
#set_property PACKAGE_PIN AH10 [get_ports {pcie_rxp[7]}]
#set_property PACKAGE_PIN AG11 [get_ports {pcie_rxn[6]}]
#set_property PACKAGE_PIN AG12 [get_ports {pcie_rxp[6]}]
#set_property PACKAGE_PIN AF9  [get_ports {pcie_rxn[5]}]
#set_property PACKAGE_PIN AF10 [get_ports {pcie_rxp[5]}]
#set_property PACKAGE_PIN AE11 [get_ports {pcie_rxn[4]}]
#set_property PACKAGE_PIN AE12 [get_ports {pcie_rxp[4]}]
#set_property PACKAGE_PIN AH5  [get_ports {pcie_rxn[3]}]
#set_property PACKAGE_PIN AH6  [get_ports {pcie_rxp[3]}]
#set_property PACKAGE_PIN AG3  [get_ports {pcie_rxn[2]}]
#set_property PACKAGE_PIN AG4  [get_ports {pcie_rxp[2]}]
#set_property PACKAGE_PIN AE3  [get_ports {pcie_rxn[1]}]
#set_property PACKAGE_PIN AE4  [get_ports {pcie_rxp[1]}]
#set_property PACKAGE_PIN AC3  [get_ports {pcie_rxn[0]}]
#set_property PACKAGE_PIN AC4  [get_ports {pcie_rxp[0]}]

#set_property PACKAGE_PIN AJ11 [get_ports {pcie_txn[7]}]
#set_property PACKAGE_PIN AJ12 [get_ports {pcie_txp[7]}]
#set_property PACKAGE_PIN AK9  [get_ports {pcie_txn[6]}]
#set_property PACKAGE_PIN AK10 [get_ports {pcie_txp[6]}]
#set_property PACKAGE_PIN AJ7  [get_ports {pcie_txn[5]}]
#set_property PACKAGE_PIN AJ8  [get_ports {pcie_txp[5]}]
#set_property PACKAGE_PIN AG7  [get_ports {pcie_txn[4]}]
#set_property PACKAGE_PIN AG8  [get_ports {pcie_txp[4]}]
#set_property PACKAGE_PIN AK5  [get_ports {pcie_txn[3]}]
#set_property PACKAGE_PIN AK6  [get_ports {pcie_txp[3]}]
#set_property PACKAGE_PIN AJ3  [get_ports {pcie_txn[2]}]
#set_property PACKAGE_PIN AJ4  [get_ports {pcie_txp[2]}]
#set_property PACKAGE_PIN AK1  [get_ports {pcie_txn[1]}]
#set_property PACKAGE_PIN AK2  [get_ports {pcie_txp[1]}]
#set_property PACKAGE_PIN AH1  [get_ports {pcie_txn[0]}]
#set_property PACKAGE_PIN AH2  [get_ports {pcie_txp[0]}]


########### --------- USB COM ------------##########
#set_property PACKAGE_PIN D16  IOSTANDARD LVCMOS25 [get_ports USB_TX]
#set_property PACKAGE_PIN D17  IOSTANDARD LVCMOS25 [get_ports USB_RX]

########### --------- I2C EEPROM ------------##########
#set_property PACKAGE_PIN C16  IOSTANDARD LVCMOS25 [get_ports SCL]
#set_property PACKAGE_PIN C17  IOSTANDARD LVCMOS25 [get_ports SDA]

########### --------- SMA ------------##########
#set_property PACKAGE_PIN C11  [get_ports sma_rxn]
#set_property PACKAGE_PIN C12  [get_ports sma_rxp]
#set_property PACKAGE_PIN A11  [get_ports sma_txn]
#set_property PACKAGE_PIN A12  [get_ports sma_txp]

########### --------- SATA ------------##########
#set_property PACKAGE_PIN B9   [get_ports sata_rxn]
#set_property PACKAGE_PIN B10  [get_ports sata_rxp]
#set_property PACKAGE_PIN E11  [get_ports sata_txn]
#set_property PACKAGE_PIN E12  [get_ports sata_txp]

########### --------- DDR3-A ------------##########
#set_property PACKAGE_PIN A21  [get_ports {ddr3a_dq[0]}]
#set_property PACKAGE_PIN A22  [get_ports {ddr3a_dq[1]}]
#set_property PACKAGE_PIN A23  [get_ports {ddr3a_dq[2]}]
#set_property PACKAGE_PIN B23  [get_ports {ddr3a_dq[3]}]
#set_property PACKAGE_PIN B19  [get_ports {ddr3a_dq[4]}]
#set_property PACKAGE_PIN C19  [get_ports {ddr3a_dq[5]}]
#set_property PACKAGE_PIN A20  [get_ports {ddr3a_dq[6]}]
#set_property PACKAGE_PIN B20  [get_ports {ddr3a_dq[7]}]
#set_property PACKAGE_PIN C21  [get_ports {ddr3a_dq[8]}]
#set_property PACKAGE_PIN C21  [get_ports {ddr3a_dq[9]}]
#set_property PACKAGE_PIN C22  [get_ports {ddr3a_dq[10]}]
#set_property PACKAGE_PIN D22  [get_ports {ddr3a_dq[11]}]
#set_property PACKAGE_PIN E18  [get_ports {ddr3a_dq[12]}]
#set_property PACKAGE_PIN D18  [get_ports {ddr3a_dq[13]}]
#set_property PACKAGE_PIN E20  [get_ports {ddr3a_dq[14]}]
#set_property PACKAGE_PIN E21  [get_ports {ddr3a_dq[15]}]
#set_property PACKAGE_PIN G18  [get_ports {ddr3a_dq[16]}]
#set_property PACKAGE_PIN F18  [get_ports {ddr3a_dq[17]}]
#set_property PACKAGE_PIN G20  [get_ports {ddr3a_dq[18]}]
#set_property PACKAGE_PIN F20  [get_ports {ddr3a_dq[19]}]
#set_property PACKAGE_PIN H20  [get_ports {ddr3a_dq[20]}]
#set_property PACKAGE_PIN G22  [get_ports {ddr3a_dq[21]}]
#set_property PACKAGE_PIN G23  [get_ports {ddr3a_dq[22]}]
#set_property PACKAGE_PIN F23  [get_ports {ddr3a_dq[23]}]
#set_property PACKAGE_PIN L18  [get_ports {ddr3a_dq[24]}]
#set_property PACKAGE_PIN J18  [get_ports {ddr3a_dq[25]}]
#set_property PACKAGE_PIN J19  [get_ports {ddr3a_dq[26]}]
#set_property PACKAGE_PIN K20  [get_ports {ddr3a_dq[27]}]
#set_property PACKAGE_PIN J22  [get_ports {ddr3a_dq[28]}]
#set_property PACKAGE_PIN H22  [get_ports {ddr3a_dq[29]}]
#set_property PACKAGE_PIN K23  [get_ports {ddr3a_dq[30]}]
#set_property PACKAGE_PIN J23  [get_ports {ddr3a_dq[31]}]
#set_property PACKAGE_PIN N24  [get_ports {ddr3a_dq[32]}]
#set_property PACKAGE_PIN N22  [get_ports {ddr3a_dq[33]}]
#set_property PACKAGE_PIN P24  [get_ports {ddr3a_dq[34]}]
#set_property PACKAGE_PIN P23  [get_ports {ddr3a_dq[35]}]
#set_property PACKAGE_PIN L20  [get_ports {ddr3a_dq[36]}]
#set_property PACKAGE_PIN M22  [get_ports {ddr3a_dq[37]}]
#set_property PACKAGE_PIN M24  [get_ports {ddr3a_dq[38]}]
#set_property PACKAGE_PIN N25  [get_ports {ddr3a_dq[39]}]
#set_property PACKAGE_PIN M17  [get_ports {ddr3a_dq[40]}]
#set_property PACKAGE_PIN N19  [get_ports {ddr3a_dq[41]}]
#set_property PACKAGE_PIN N17  [get_ports {ddr3a_dq[42]}]
#set_property PACKAGE_PIN P17  [get_ports {ddr3a_dq[43]}]
#set_property PACKAGE_PIN N20  [get_ports {ddr3a_dq[44]}]
#set_property PACKAGE_PIN N21  [get_ports {ddr3a_dq[45]}]
#set_property PACKAGE_PIN P21  [get_ports {ddr3a_dq[46]}]
#set_property PACKAGE_PIN P19  [get_ports {ddr3a_dq[47]}]
#set_property PACKAGE_PIN K26  [get_ports {ddr3a_dq[48]}]
#set_property PACKAGE_PIN K25  [get_ports {ddr3a_dq[49]}]
#set_property PACKAGE_PIN L26  [get_ports {ddr3a_dq[50]}]
#set_property PACKAGE_PIN L25  [get_ports {ddr3a_dq[51]}]
#set_property PACKAGE_PIN M25  [get_ports {ddr3a_dq[52]}]
#set_property PACKAGE_PIN N26  [get_ports {ddr3a_dq[53]}]
#set_property PACKAGE_PIN P28  [get_ports {ddr3a_dq[54]}]
#set_property PACKAGE_PIN P27  [get_ports {ddr3a_dq[55]}]
#set_property PACKAGE_PIN L30  [get_ports {ddr3a_dq[56]}]
#set_property PACKAGE_PIN M29  [get_ports {ddr3a_dq[57]}]
#set_property PACKAGE_PIN P29  [get_ports {ddr3a_dq[58]}]
#set_property PACKAGE_PIN R29  [get_ports {ddr3a_dq[59]}]
#set_property PACKAGE_PIN K28  [get_ports {ddr3a_dq[60]}]
#set_property PACKAGE_PIN K29  [get_ports {ddr3a_dq[61]}]
#set_property PACKAGE_PIN K30  [get_ports {ddr3a_dq[62]}]
#set_property PACKAGE_PIN M28  [get_ports {ddr3a_dq[63]}]
#set_property SLEW FAST [get_ports {ddr3a_dq[*]}]
#set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3a_dq[*]}]
#set_property IOSTANDARD SSTL15 [get_ports {ddr3a_dq[*]}]

#set_property PACKAGE_PIN F25 [get_ports {ddr3a_addr[14]}]
#set_property PACKAGE_PIN H29 [get_ports {ddr3a_addr[13]}]
#set_property PACKAGE_PIN A28 [get_ports {ddr3a_addr[12]}]
#set_property PACKAGE_PIN E26 [get_ports {ddr3a_addr[11]}]
#set_property PACKAGE_PIN E30 [get_ports {ddr3a_addr[10]}]
#set_property PACKAGE_PIN B30 [get_ports {ddr3a_addr[9]}]
#set_property PACKAGE_PIN C29 [get_ports {ddr3a_addr[8]}]
#set_property PACKAGE_PIN B28 [get_ports {ddr3a_addr[7]}]
#set_property PACKAGE_PIN A30 [get_ports {ddr3a_addr[6]}]
#set_property PACKAGE_PIN C30 [get_ports {ddr3a_addr[5]}]
#set_property PACKAGE_PIN B29 [get_ports {ddr3a_addr[4]}]
#set_property PACKAGE_PIN D29 [get_ports {ddr3a_addr[3]}]
#set_property PACKAGE_PIN F26 [get_ports {ddr3a_addr[2]}]
#set_property PACKAGE_PIN E29 [get_ports {ddr3a_addr[1]}]
#set_property PACKAGE_PIN F28 [get_ports {ddr3a_addr[0]}]
#set_property SLEW FAST [get_ports {ddr3a_addr[*]}]
#set_property IOSTANDARD SSTL15 [get_ports {ddr3a_addr[*]}]

#set_property PACKAGE_PIN E28 [get_ports {ddr3a_ba[2]}]
#set_property PACKAGE_PIN G28 [get_ports {ddr3a_ba[1]}]
#set_property PACKAGE_PIN F30 [get_ports {ddr3a_ba[0]}]
#set_property SLEW FAST [get_ports {ddr3a_ba[*]}]
#set_property IOSTANDARD SSTL15 [get_ports {ddr3a_ba[*]}]

#set_property PACKAGE_PIN H27  SLEW FAST  IOSTANDARD SSTL15 [get_ports ddr3a_ras_n]
#set_property PACKAGE_PIN G30  SLEW FAST  IOSTANDARD SSTL15 [get_ports ddr3a_cas_n]
#set_property PACKAGE_PIN G29  SLEW FAST  IOSTANDARD SSTL15 [get_ports ddr3a_we_n]
#set_property PACKAGE_PIN F27  SLEW FAST  IOSTANDARD LVCMOS15 [get_ports ddr3a_reset_n]
#set_property PACKAGE_PIN G25  SLEW FAST  IOSTANDARD SSTL15 [get_ports {ddr3a_cke[0]}]
#set_property PACKAGE_PIN J28  SLEW FAST  IOSTANDARD SSTL15 [get_ports {ddr3a_odt[0]}]
#set_property PACKAGE_PIN H30  SLEW FAST  IOSTANDARD SSTL15 [get_ports {ddr3a_cs_n[0]}]

#set_property PACKAGE_PIN B22 [get_ports {ddr3a_dm[0]}]
#set_property PACKAGE_PIN E19 [get_ports {ddr3a_dm[1]}]
#set_property PACKAGE_PIN F22 [get_ports {ddr3a_dm[2]}]
#set_property PACKAGE_PIN K19 [get_ports {ddr3a_dm[3]}]
#set_property PACKAGE_PIN M23 [get_ports {ddr3a_dm[4]}]
#set_property PACKAGE_PIN P18 [get_ports {ddr3a_dm[5]}]
#set_property PACKAGE_PIN P26 [get_ports {ddr3a_dm[6]}]
#set_property PACKAGE_PIN N29 [get_ports {ddr3a_dm[7]}]
#set_property SLEW FAST [get_ports {ddr3a_dm[*]}]
#set_property IOSTANDARD SSTL15 [get_ports {ddr3a_dm[*]}]

#set_property PACKAGE_PIN A18 [get_ports {ddr3a_dqs_n[0]}]
#set_property PACKAGE_PIN B18 [get_ports {ddr3a_dqs_p[0]}]
#set_property PACKAGE_PIN D23 [get_ports {ddr3a_dqs_n[1]}]
#set_property PACKAGE_PIN E23 [get_ports {ddr3a_dqs_p[1]}]
#set_property PACKAGE_PIN G19 [get_ports {ddr3a_dqs_n[2]}]
#set_property PACKAGE_PIN H19 [get_ports {ddr3a_dqs_p[2]}]
#set_property PACKAGE_PIN J21 [get_ports {ddr3a_dqs_n[3]}]
#set_property PACKAGE_PIN K21 [get_ports {ddr3a_dqs_p[3]}]
#set_property PACKAGE_PIN K24 [get_ports {ddr3a_dqs_n[4]}]
#set_property PACKAGE_PIN L23 [get_ports {ddr3a_dqs_p[4]}]
#set_property PACKAGE_PIN M19 [get_ports {ddr3a_dqs_n[5]}]
#set_property PACKAGE_PIN M18 [get_ports {ddr3a_dqs_p[5]}]
#set_property PACKAGE_PIN M27 [get_ports {ddr3a_dqs_n[6]}]
#set_property PACKAGE_PIN N27 [get_ports {ddr3a_dqs_p[6]}]
#set_property PACKAGE_PIN M30 [get_ports {ddr3a_dqs_n[7]}]
#set_property PACKAGE_PIN N30 [get_ports {ddr3a_dqs_p[7]}]
#set_property SLEW FAST [get_ports {ddr3a_dqs_n[*]}]
#set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3a_dqs_n[*]}]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3a_dqs_n[*]}]
#set_property SLEW FAST [get_ports {ddr3a_dqs_p[*]}]
#set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3a_dqs_p[*]}]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3a_dqs_p[*]}]

#set_property PACKAGE_PIN J27  SLEW FAST IOSTANDARD DIFF_SSTL15 [get_ports {ddr3a_ck_n[0]}]
#set_property PACKAGE_PIN J26  SLEW FAST IOSTANDARD DIFF_SSTL15 [get_ports {ddr3a_ck_p[0]}]

########### --------- DDR3-B ------------##########
#set_property PACKAGE_PIN W29  [get_ports {ddr3b_dq[0]}]
#set_property PACKAGE_PIN Y29  [get_ports {ddr3b_dq[1]}]
#set_property PACKAGE_PIN AB30 [get_ports {ddr3b_dq[2]}]
#set_property PACKAGE_PIN AB29 [get_ports {ddr3b_dq[3]}]
#set_property PACKAGE_PIN W28  [get_ports {ddr3b_dq[4]}]
#set_property PACKAGE_PIN W26  [get_ports {ddr3b_dq[5]}]
#set_property PACKAGE_PIN Y28  [get_ports {ddr3b_dq[6]}]
#set_property PACKAGE_PIN AB28 [get_ports {ddr3b_dq[7]}]
#set_property PACKAGE_PIN AA25 [get_ports {ddr3b_dq[8]}]
#set_property PACKAGE_PIN AD27 [get_ports {ddr3b_dq[9]}]
#set_property PACKAGE_PIN AB24 [get_ports {ddr3b_dq[10]}]
#set_property PACKAGE_PIN AC24 [get_ports {ddr3b_dq[11]}]
#set_property PACKAGE_PIN Y26  [get_ports {ddr3b_dq[12]}]
#set_property PACKAGE_PIN Y25  [get_ports {ddr3b_dq[13]}]
#set_property PACKAGE_PIN AA26 [get_ports {ddr3b_dq[14]}]
#set_property PACKAGE_PIN AC26 [get_ports {ddr3b_dq[15]}]
#set_property PACKAGE_PIN AD29 [get_ports {ddr3b_dq[16]}]
#set_property PACKAGE_PIN AE30 [get_ports {ddr3b_dq[17]}]
#set_property PACKAGE_PIN AE29 [get_ports {ddr3b_dq[18]}]
#set_property PACKAGE_PIN AF30 [get_ports {ddr3b_dq[19]}]
#set_property PACKAGE_PIN AD28 [get_ports {ddr3b_dq[20]}]
#set_property PACKAGE_PIN AC27 [get_ports {ddr3b_dq[21]}]
#set_property PACKAGE_PIN AF28 [get_ports {ddr3b_dq[22]}]
#set_property PACKAGE_PIN AF27 [get_ports {ddr3b_dq[23]}]
#set_property PACKAGE_PIN AG30 [get_ports {ddr3b_dq[24]}]
#set_property PACKAGE_PIN AG29 [get_ports {ddr3b_dq[25]}]
#set_property PACKAGE_PIN AH29 [get_ports {ddr3b_dq[26]}]
#set_property PACKAGE_PIN AJ29 [get_ports {ddr3b_dq[27]}]
#set_property PACKAGE_PIN AK30 [get_ports {ddr3b_dq[28]}]
#set_property PACKAGE_PIN AK29 [get_ports {ddr3b_dq[29]}]
#set_property PACKAGE_PIN AK28 [get_ports {ddr3b_dq[30]}]
#set_property PACKAGE_PIN AG27 [get_ports {ddr3b_dq[31]}]
#set_property PACKAGE_PIN AD18 [get_ports {ddr3b_dq[32]}]
#set_property PACKAGE_PIN AD19 [get_ports {ddr3b_dq[33]}]
#set_property PACKAGE_PIN AA18 [get_ports {ddr3b_dq[34]}]
#set_property PACKAGE_PIN Y18  [get_ports {ddr3b_dq[35]}]
#set_property PACKAGE_PIN AE18 [get_ports {ddr3b_dq[36]}]
#set_property PACKAGE_PIN Y19  [get_ports {ddr3b_dq[37]}]
#set_property PACKAGE_PIN AB17 [get_ports {ddr3b_dq[38]}]
#set_property PACKAGE_PIN AA17 [get_ports {ddr3b_dq[39]}]
#set_property PACKAGE_PIN AH20 [get_ports {ddr3b_dq[40]}]
#set_property PACKAGE_PIN AH19 [get_ports {ddr3b_dq[41]}]
#set_property PACKAGE_PIN AG19 [get_ports {ddr3b_dq[42]}]
#set_property PACKAGE_PIN AF18 [get_ports {ddr3b_dq[43]}]
#set_property PACKAGE_PIN AJ18 [get_ports {ddr3b_dq[44]}]
#set_property PACKAGE_PIN AK18 [get_ports {ddr3b_dq[45]}]
#set_property PACKAGE_PIN AJ17 [get_ports {ddr3b_dq[46]}]
#set_property PACKAGE_PIN AJ16 [get_ports {ddr3b_dq[47]}]
#set_property PACKAGE_PIN AF16 [get_ports {ddr3b_dq[48]}]
#set_property PACKAGE_PIN AE16 [get_ports {ddr3b_dq[49]}]
#set_property PACKAGE_PIN AE15 [get_ports {ddr3b_dq[50]}]
#set_property PACKAGE_PIN AF15 [get_ports {ddr3b_dq[51]}]
#set_property PACKAGE_PIN AC15 [get_ports {ddr3b_dq[52]}]
#set_property PACKAGE_PIN AB15 [get_ports {ddr3b_dq[53]}]
#set_property PACKAGE_PIN AC14 [get_ports {ddr3b_dq[54]}]
#set_property PACKAGE_PIN AB14 [get_ports {ddr3b_dq[55]}]
#set_property PACKAGE_PIN AH17 [get_ports {ddr3b_dq[56]}]
#set_property PACKAGE_PIN AH16 [get_ports {ddr3b_dq[57]}]
#set_property PACKAGE_PIN AK14 [get_ports {ddr3b_dq[58]}]
#set_property PACKAGE_PIN AJ14 [get_ports {ddr3b_dq[59]}]
#set_property PACKAGE_PIN AF17 [get_ports {ddr3b_dq[60]}]
#set_property PACKAGE_PIN AG17 [get_ports {ddr3b_dq[61]}]
#set_property PACKAGE_PIN AH15 [get_ports {ddr3b_dq[62]}]
#set_property PACKAGE_PIN AH14 [get_ports {ddr3b_dq[63]}]
#set_property SLEW FAST [get_ports {ddr3b_dq[*]}]
#set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3b_dq[*]}]
#set_property IOSTANDARD SSTL15 [get_ports {ddr3b_dq[*]}]

#set_property PACKAGE_PIN AK24 [get_ports {ddr3b_addr[14]}]
#set_property PACKAGE_PIN AD22 [get_ports {ddr3b_addr[13]}]
#set_property PACKAGE_PIN AD21 [get_ports {ddr3b_addr[12]}]
#set_property PACKAGE_PIN AK25 [get_ports {ddr3b_addr[11]}]
#set_property PACKAGE_PIN AJ22 [get_ports {ddr3b_addr[10]}]
#set_property PACKAGE_PIN AB23 [get_ports {ddr3b_addr[9]}]
#set_property PACKAGE_PIN AE23 [get_ports {ddr3b_addr[8]}]
#set_property PACKAGE_PIN AJ24 [get_ports {ddr3b_addr[7]}]
#set_property PACKAGE_PIN AF23 [get_ports {ddr3b_addr[6]}]
#set_property PACKAGE_PIN AD23 [get_ports {ddr3b_addr[5]}]
#set_property PACKAGE_PIN AG23 [get_ports {ddr3b_addr[4]}]
#set_property PACKAGE_PIN AJ26 [get_ports {ddr3b_addr[3]}]
#set_property PACKAGE_PIN AF22 [get_ports {ddr3b_addr[2]}]
#set_property PACKAGE_PIN AJ23 [get_ports {ddr3b_addr[1]}]
#set_property PACKAGE_PIN AG22 [get_ports {ddr3b_addr[0]}]
#set_property SLEW FAST [get_ports {ddr3b_addr[*]}]
#set_property IOSTANDARD SSTL15 [get_ports {ddr3b_addr[*]}]

#set_property PACKAGE_PIN AC21 [get_ports {ddr3b_ba[2]}]
#set_property PACKAGE_PIN AF21 [get_ports {ddr3b_ba[1]}]
#set_property PACKAGE_PIN AK23 [get_ports {ddr3b_ba[0]}]
#set_property SLEW FAST [get_ports {ddr3b_ba[*]}]
#set_property IOSTANDARD SSTL15 [get_ports {ddr3b_ba[*]}]

#set_property PACKAGE_PIN AF20 SLEW FAST  IOSTANDARD SSTL15 [get_ports ddr3b_ras_n]
#set_property PACKAGE_PIN AK21 SLEW FAST  IOSTANDARD SSTL15 [get_ports ddr3b_cas_n]
#set_property PACKAGE_PIN AJ21 SLEW FAST  IOSTANDARD SSTL15 [get_ports ddr3b_we_n]
#set_property PACKAGE_PIN Y21  SLEW FAST  IOSTANDARD LVCMOS15 [get_ports ddr3b_reset_n]
#set_property PACKAGE_PIN AB22 SLEW FAST  IOSTANDARD SSTL15 [get_ports {ddr3b_cke[0]}]
#set_property PACKAGE_PIN AG20  SLEW FAST  IOSTANDARD SSTL15 [get_ports {ddr3b_odt[0]}]
#set_property PACKAGE_PIN AE21  SLEW FAST  IOSTANDARD SSTL15 [get_ports {ddr3b_cs_n[0]}]

#set_property PACKAGE_PIN AA28 [get_ports {ddr3b_dm[0]}]
#set_property PACKAGE_PIN AA27 [get_ports {ddr3b_dm[1]}]
#set_property PACKAGE_PIN AE28 [get_ports {ddr3b_dm[2]}]
#set_property PACKAGE_PIN AH30 [get_ports {ddr3b_dm[3]}]
#set_property PACKAGE_PIN AB18 [get_ports {ddr3b_dm[4]}]
#set_property PACKAGE_PIN AJ19 [get_ports {ddr3b_dm[5]}]
#set_property PACKAGE_PIN AD14 [get_ports {ddr3b_dm[6]}]
#set_property PACKAGE_PIN AK16 [get_ports {ddr3b_dm[7]}]
#set_property SLEW FAST [get_ports {ddr3b_dm[*]}]
#set_property IOSTANDARD SSTL15 [get_ports {ddr3b_dm[*]}]

#set_property PACKAGE_PIN AA30 [get_ports {ddr3b_dqs_n[0]}]
#set_property PACKAGE_PIN Y30  [get_ports {ddr3b_dqs_p[0]}]
#set_property PACKAGE_PIN AC25 [get_ports {ddr3b_dqs_n[1]}]
#set_property PACKAGE_PIN AB25 [get_ports {ddr3b_dqs_p[1]}]
#set_property PACKAGE_PIN AC30 [get_ports {ddr3b_dqs_n[2]}]
#set_property PACKAGE_PIN AC29 [get_ports {ddr3b_dqs_p[2]}]
#set_property PACKAGE_PIN AJ28 [get_ports {ddr3b_dqs_n[3]}]
#set_property PACKAGE_PIN AJ27 [get_ports {ddr3b_dqs_p[3]}]
#set_property PACKAGE_PIN AD17 [get_ports {ddr3b_dqs_n[4]}]
#set_property PACKAGE_PIN AC17 [get_ports {ddr3b_dqs_p[4]}]
#set_property PACKAGE_PIN AK20 [get_ports {ddr3b_dqs_n[5]}]
#set_property PACKAGE_PIN AK19 [get_ports {ddr3b_dqs_p[5]}]
#set_property PACKAGE_PIN AD16 [get_ports {ddr3b_dqs_n[6]}]
#set_property PACKAGE_PIN AC16 [get_ports {ddr3b_dqs_p[6]}]
#set_property PACKAGE_PIN AG15 [get_ports {ddr3b_dqs_n[7]}]
#set_property PACKAGE_PIN AG14 [get_ports {ddr3b_dqs_p[7]}]
#set_property SLEW FAST [get_ports {ddr3b_dqs_n[*]}]
#set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3b_dqs_n[*]}]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3b_dqs_n[*]}]
#set_property SLEW FAST [get_ports {ddr3b_dqs_p[*]}]
#set_property IN_TERM UNTUNED_SPLIT_50 [get_ports {ddr3b_dqs_p[*]}]
#set_property IOSTANDARD DIFF_SSTL15 [get_ports {ddr3b_dqs_p[*]}]

#set_property PACKAGE_PIN AA23 SLEW FAST IOSTANDARD DIFF_SSTL15 [get_ports {ddr3b_ck_n[0]}]
#set_property PACKAGE_PIN AA22 SLEW FAST IOSTANDARD DIFF_SSTL15 [get_ports {ddr3b_ck_p[0]}]


#set_clock_groups -name async_clock -asynchronous -group [get_clocks [get_clocks -of_objects [get_pins clk_wiz_0/inst/mmcm_adv_inst/CLKOUT0]]] -group [get_clocks gtrefclk0_p]



#set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
#set_property BITSTREAM.CONFIG.CCLK_TRISTATE TRUE [current_design]
#set_property BITSTREAM.CONFIG.CONFIGRATE 66 [current_design]
#set_property CONFIG_VOLTAGE 2.5 [current_design]
#set_property CFGBVS VCCO [current_design]
#set_property BITSTREAM.CONFIG.SPI_32BIT_ADDR YES [current_design]
#set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]
#set_property BITSTREAM.CONFIG.SPI_FALL_EDGE YES [current_design]
#set_property BITSTREAM.CONFIG.UNUSEDPIN PULLUP [current_design]
